/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuController;
import Models.Data.Drink;
import Models.Data.Menu;
import Models.MenuModel;
import java.awt.Color;
import java.util.HashSet;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author nguye
 */
public class MenuManager extends javax.swing.JFrame {
    public static int IdFood;
    /**
     * Creates new form MenuManager
     */
    public MenuManager() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Color color = new Color(254, 231, 199);
        getContentPane().setBackground(color);
        Color color_btn = new Color(173, 121, 91);
        btn_Search.setBackground(color_btn);
        btn_Search.setForeground(Color.WHITE);
        btn__Add.setBackground(color_btn);
        btn__Add.setForeground(Color.WHITE);
        btn__Exit.setBackground(color_btn);
        btn__Exit.setForeground(Color.WHITE);
        btn__Update.setBackground(color_btn);
        btn__Update.setForeground(Color.WHITE);

        
        MenuModel menuModel = new MenuModel();
        MenuController menuController = new MenuController(menuModel);
        Menu menu = new Menu();
        List<Menu> listMenu = menuController.getAllMenuManager();
        DefaultTableModel model = (DefaultTableModel)jTbl_Menu.getModel();
        
        TableColumnModel columnModel = jTbl_Menu.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        
        int i = 0;
        for(Menu o : listMenu){
            String status;
            if (o.getStatus() == 0) {
                status = "Đang kinh doanh";
            } else {
                status = "Tạm dừng bán";
            }
            model.addRow(new Object[] {
                o.getId(),
                o.getNameDrink(),
                o.getPrice(),
                o.getNameType(),
                status
            });
            i++;
        }
        lbl_QuantityFood.setText("Số món ăn đang kinh doanh: "+i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Menu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl_QuantityFood = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btn__Update = new javax.swing.JButton();
        btn__Add = new javax.swing.JButton();
        btn__Exit = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTbl_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món ăn", "Tên món ăn", "Đơn giá", "Loại món", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTbl_Menu.setName(""); // NOI18N
        jTbl_Menu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTbl_Menu);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý thực đơn");

        lbl_QuantityFood.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_QuantityFood.setText("Số món ăn đang kinh doanh: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Danh sách món ăn");

        txtSearch.setText("Tìm kiếm...");

        btn__Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change.png"))); // NOI18N
        btn__Update.setText("Sửa thông tin");
        btn__Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__UpdateActionPerformed(evt);
            }
        });

        btn__Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/online-order.png"))); // NOI18N
        btn__Add.setText("Thêm món ăn");
        btn__Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__AddActionPerformed(evt);
            }
        });

        btn__Exit.setText("Trở về");
        btn__Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__ExitActionPerformed(evt);
            }
        });

        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loupe (1).png"))); // NOI18N
        btn_Search.setText("Tìm kiếm");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_QuantityFood, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(btn__Add, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(btn__Update, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btn__Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_QuantityFood)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search)
                    .addComponent(btn__Add)
                    .addComponent(btn__Update)
                    .addComponent(btn__Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn__ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__ExitActionPerformed
        // TODO add your handling code here:
        HomeStaff homeStaffFrame = new HomeStaff();
        homeStaffFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn__ExitActionPerformed

    private void btn__AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__AddActionPerformed
        // TODO add your handling code here:
        AddFood addfoodFrame = new AddFood();
        addfoodFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn__AddActionPerformed

    private void btn__UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__UpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTbl_Menu.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy giá trị của ô "Id" từ dòng được chọn
            int id = (int) jTbl_Menu.getValueAt(selectedRow, 0);
            IdFood = id;
            UpdateFood updateFood = new UpdateFood();
            updateFood.setVisible(true);
            this.setVisible(false);
        } else {
            // Hiển thị thông báo hoặc xử lý khi không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm bạn muốn sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn__UpdateActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        if(txtSearch.getText() == null || txtSearch.getText() == "") {
            MenuModel menuModel = new MenuModel();
            MenuController menuController = new MenuController(menuModel);
            Menu menu = new Menu();
            List<Menu> listMenu = menuController.getAllMenuManager();
            DefaultTableModel model = (DefaultTableModel)jTbl_Menu.getModel();
            int i = 0;
            for(Menu o : listMenu){
                String status;
                if (o.getStatus() == 0) {
                    status = "Đang kinh doanh";
                } else {
                    status = "Tạm dừng bán";
                }
                model.addRow(new Object[] {
                    o.getId(),
                    o.getNameDrink(),
                    o.getPrice(),
                    o.getNameType(),
                    status
                });
                i++;
            }
            lbl_QuantityFood.setText("Số món ăn đang kinh doanh: "+i);
        }
        else {
            MenuModel menuModel = new MenuModel();
            MenuController menuController = new MenuController(menuModel);
            Menu menu = new Menu();
            List<Menu> listMenu = menuController.FindMenuById(txtSearch.getText());
            DefaultTableModel model = (DefaultTableModel)jTbl_Menu.getModel();
            model.setRowCount(0);
            
            int i = 0;
            for(Menu o : listMenu){
                String status;
                if (o.getStatus() == 0) {
                    status = "Đang kinh doanh";
                } else {
                    status = "Tạm dừng bán";
                }
                model.addRow(new Object[] {
                    o.getId(),
                    o.getNameDrink(),
                    o.getPrice(),
                    o.getNameType(),
                    status
                });
                i++;
            }
            lbl_QuantityFood.setText("Số món ăn đang kinh doanh: "+i);
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn__Add;
    private javax.swing.JButton btn__Exit;
    private javax.swing.JButton btn__Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Menu;
    private javax.swing.JLabel lbl_QuantityFood;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
