/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HrManagerController;
import Models.Data.Staff;
import Models.HRManagerModel;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class UpdateStaff extends javax.swing.JFrame {
    
    /**
     * Creates new form UpdateStaff
     */
    public UpdateStaff() {
        initComponents();
        
        Color color = new Color(254, 231, 199);
        getContentPane().setBackground(color);
        Color color_btn = new Color(173, 121, 91);
        btn_Save.setBackground(color_btn);
        btn_Save.setForeground(Color.WHITE);
        btn_Exit.setBackground(color_btn);
        btn_Exit.setForeground(Color.WHITE);
        
        
        
        int IdStaff = HrManager.IdStaff;
        HRManagerModel hrManagerModel = new HRManagerModel();
        HrManagerController hrManagerController = new HrManagerController(hrManagerModel);
        Staff staff = hrManagerController.GetStaffById(IdStaff);
        txt_Id.setText(String.valueOf(staff.iD));
        lbl__FirstName.setText(staff.firstName);
        lbl__LastName.setText(staff.lastName);
        jDC_DOB.setDate(staff.dob);
        lbl__PhoneNumber.setText(String.valueOf(staff.phoneNumber));
        lbl__UserName1.setText((staff.Email));
        Date date = new Date();
        if(staff.hireDate == null) {
            jDC_HireDate.setDate(date);
        }
        else {
            jDC_HireDate.setDate(staff.hireDate);
        }
        lbl__Salary.setText(String.valueOf(staff.salary));
        
        buttonGroup1.add(jCB_Dismissal);
        buttonGroup1.add(jCB_Dismissal1);
        
        String gioitinh = staff.getGender();
        if(gioitinh == "Nam") {
            Nam.setVisible(true);
            Nu.setVisible(false);
        }
        else {
            Nam.setVisible(false);
            Nu.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl_AddFood1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl__FirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl__LastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbb__Gender = new javax.swing.JComboBox<>();
        jDC_DOB = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        lbl__PhoneNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl__Salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDC_HireDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cbb__Position = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        lbl__UserName1 = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jCB_Dismissal = new javax.swing.JCheckBox();
        jCB_Dismissal1 = new javax.swing.JCheckBox();
        Nam = new javax.swing.JLabel();
        Nu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_AddFood1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_AddFood1.setText("Sửa nhân viên");

        jLabel2.setText("Họ");

        jLabel3.setText("Tên");

        jLabel4.setText("Ngày sinh");

        jLabel6.setText("Giới tính");

        cbb__Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbb__Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb__GenderActionPerformed(evt);
            }
        });

        jDC_DOB.setDateFormatString("dd MMM, yyyy");

        jLabel5.setText("Số điện thoại");

        jLabel12.setText("Email");

        jLabel13.setText("Ngày vào làm");

        jDC_HireDate.setDateFormatString("dd MMM, yyyy");

        jLabel7.setText("Chức vụ");

        cbb__Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Thu ngân", "Phục vụ" }));

        jLabel14.setText("Lương");

        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Exit.setText("Thoát");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Mã nhân viên");

        txt_Id.setEnabled(false);

        jCB_Dismissal.setText("Sa thải");

        jCB_Dismissal1.setText("Tạm nghỉ");
        jCB_Dismissal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_Dismissal1ActionPerformed(evt);
            }
        });

        Nam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parkbogum.jpg"))); // NOI18N

        Nu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/karina1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbl_AddFood1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl__FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lbl__LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDC_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(cbb__Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl__PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl__UserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDC_HireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(cbb__Position, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(lbl__Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jCB_Dismissal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(jCB_Dismissal1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245)
                .addComponent(btn_Exit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_AddFood1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl__FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl__LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDC_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb__Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(lbl__PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(lbl__UserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDC_HireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb__Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(lbl__Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Dismissal)
                    .addComponent(jCB_Dismissal1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Save)
                    .addComponent(btn_Exit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        int state = 0;
        if(jCB_Dismissal.isSelected()) {
            state = 1;
        }
        else if(jCB_Dismissal1.isSelected()) {
            state = 2;
        }
        HRManagerModel hRManagerModel = new HRManagerModel();
        HrManagerController hrManagerController = new HrManagerController(hRManagerModel);
        Staff staff = new Staff();
        staff.setiD(HrManager.IdStaff);
        staff.setFirstName(lbl__FirstName.getText());
        staff.setLastName(lbl__LastName.getText());
        Date selectDate = jDC_DOB.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dates = dateFormat.format(selectDate);
        java.sql.Date sqlDate = new java.sql.Date(selectDate.getTime());
        staff.setDob(sqlDate);
        staff.setGender(cbb__Gender.getSelectedItem().toString());
        staff.setPhoneNumber(Integer.parseInt(lbl__PhoneNumber.getText()));
        staff.setEmail(lbl__UserName1.getText());
        Date HireDate = jDC_HireDate.getDate();
        java.sql.Date HireDateSql = new java.sql.Date(HireDate.getTime());
        staff.setHireDate(HireDateSql);
        staff.setPosition(cbb__Position.getSelectedItem().toString());
        staff.setSalary(BigDecimal.valueOf(Double.parseDouble(lbl__Salary.getText())));
        staff.setState(state);
        if(hrManagerController.UpdateStaff(staff)) {
            JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            HrManager hrManager = new HrManager();
            hrManager.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        HrManager hrManager = new HrManager();
        hrManager.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void jCB_Dismissal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_Dismissal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_Dismissal1ActionPerformed

    private void cbb__GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb__GenderActionPerformed
        // TODO add your handling code here:
        String gioitinh = cbb__Gender.getSelectedItem().toString();
        if(gioitinh == "Nam") {
            Nam.setVisible(true);
            Nu.setVisible(false);
        }
        else {
            Nam.setVisible(false);
            Nu.setVisible(true);
        }
    }//GEN-LAST:event_cbb__GenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nam;
    private javax.swing.JLabel Nu;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbb__Gender;
    private javax.swing.JComboBox<String> cbb__Position;
    private javax.swing.JCheckBox jCB_Dismissal;
    private javax.swing.JCheckBox jCB_Dismissal1;
    private com.toedter.calendar.JDateChooser jDC_DOB;
    private com.toedter.calendar.JDateChooser jDC_HireDate;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_AddFood1;
    private javax.swing.JTextField lbl__FirstName;
    private javax.swing.JTextField lbl__LastName;
    private javax.swing.JTextField lbl__PhoneNumber;
    private javax.swing.JTextField lbl__Salary;
    private javax.swing.JTextField lbl__UserName1;
    private javax.swing.JTextField txt_Id;
    // End of variables declaration//GEN-END:variables
}
